services:
  dm-backend:
    build: .
    # image: "backend-backoffice:latest"
    networks:
      - dm-network
    ports:
      - "8080:8080"
    environment:
      DATABASE_URL: jdbc:mysql://mysql:3306/dm_db
      DATABASE_USERNAME: root
      DATABASE_PASSWORD: test
    depends_on:
      - mysql

  mysql:
    image: mysql:8.1
    networks:
      - dm-network
    container_name: dm_db-mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: test
      MYSQL_DATABASE: dm_db
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql

networks:
  dm-network:
    driver: bridge

volumes:
  mysql-data:
