services:
  dm-backend:
    build: .
    # image: "backend-backoffice:latest"
    networks:
      - dm-network
    ports:
      - "8080:8080"
    environment:
      DATABASE_URL: jdbc:postgresql://postgres:5432/dm_db
      DATABASE_USERNAME: test
      DATABASE_PASSWORD: test
    depends_on:
      - postgres

  postgres:
    image: postgres:16.1-alpine
    networks:
      - dm-network
    container_name: dm_db-postgres
    restart: always
    environment:
      POSTGRES_USER: test
      POSTGRES_PASSWORD: test
      POSTGRES_DB: dm_db
      POSTGRES_INITDB_ARGS: '--encoding=UTF-8 --lc-collate=C --lc-ctype=C'
    # volumes:
    #   - postgres:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  pgadmin:
    image: dpage/pgadmin4:8.7
    networks:
      - dm-network
    restart: always
    container_name: dm_db-pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@email.com
      PGADMIN_DEFAULT_PASSWORD: admin
    # volumes:
    #   - pgadmin:/var/lib/pgadmin
    ports:
      - "8081:80"
    depends_on:
      - postgres

networks:
  dm-network:
    driver: bridge

volumes:
  postgres:
  pgadmin:
